title: My Web page
author: Matt-deve
email: email not supplied at present
description: > # this means to ignore newlines until "baseurl:"
  Testing out the Github pages.
theme: minima

# social links
twitter_username: Not on twitter...
github_username:  Matt-deve

show_excerpts: true # set to false to remove excerpts on the homepage
